### ISSUE TITLE
Conflict resolution

### ISSUE THREAD

**Issue by ugajin-nijagu** [OmarShehata/basic-networking#1]
I found your ‘barebones’ example, which pleased me a lot, as I like simplicity.  

However, I have only one computer, and so only one client is ever in focus at any one time, so I cannot easily [if at all] create test conditions necessary to see what happens if two [or more] players mouse down together, at the same time. 

I suspect that we might cause a crash, or something. Have you run such a test, and if so what was the result?

Thanking you in anticipation.

-u

**Comment by OmarShehata** [comment]
I'm glad you liked this example @ugajin-nijagu ! I originally made it just as a reference to myself, but I'm happy to hear you found it useful.

I hadn't thought of this particular case, but I just tried it out, and here's what happens: 

![flickering](https://i.imgur.com/vQ0lJUR.gif)

Where I'm holding down and moving the mouse on two computers.

It will never crash because even if two clients click simultaneously, that doesn't mean both messages will reach the server at the same time.  Even if both messages arrive at the server at the same time, they have to get processed and broadcast to other clients. I believe socket.io does this asynchronously in parallel/with multiple threads. But even so, at the end of this chain, the code that runs on the client, in the browser, does not run in parallel, and so one of those messages will be processed last, and the circle will render at that last location. 

Does that answer your question?

**Comment by ugajin-nijagu** [comment]
Thanks, that's very kind... latency!
